# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce0e9398cd6e9f6f447d8701db46afeb6da13079e43b10a13fffb3b997c831942e09005930d23b760b684afdf80ade31c9cd35c793b9ce6ae48eb34a9cc7d6c

test:
  secret_key_base: 219358f7e48cae142590fcefb0fc43830f60ad4dbb0e1e25f830bbecf79960002498496487957d2a62a9c40bb3fd5509bcee3d499c09832ed3a838aefcc1cc98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
